global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "node_exporter"
    static_configs:
      - targets: ["node_exporter:9100"]

  - job_name: "nginx"
    static_configs:
      - targets: ["nginx_exporter:9113"]

  - job_name: "mysql"
    static_configs:
      - targets: ["mysqld_exporter:9104"]

  - job_name: "mongodb"
    static_configs:
      - targets: ["mongodb_exporter:9216"]
